"""Tests for build utility helper functions.

Generated by our friend.
"""

from pathlib import Path

from ax_prover.models.files import Location
from ax_prover.models.messages import ProposalMessage
from ax_prover.models.proving import TargetItem
from ax_prover.utils.build import TemporaryProposal, _format_lean_errors, _trim_warnings


class TestTrimWarnings:
    """Tests for _trim_warnings function."""

    def test_removes_warning_lines(self):
        """Lines containing 'warning:' are removed."""
        output = "error: type mismatch\nwarning: unused import\nother line"
        result = _trim_warnings(output)
        assert "warning:" not in result
        assert "error: type mismatch" in result
        assert "other line" in result

    def test_removes_sorry_warnings(self):
        """Lines about sorry usage are removed."""
        output = "declaration uses 'sorry'\nerror: real error"
        result = _trim_warnings(output)
        assert "sorry" not in result
        assert "real error" in result

    def test_removes_unused_variable_warnings(self):
        """Lines about unused variables are removed."""
        output = "unused variable `h`\ndef foo := 1"
        result = _trim_warnings(output)
        assert "unused variable" not in result

    def test_preserves_error_lines(self):
        """Error lines without warning keywords are preserved."""
        output = "error: unknown identifier 'foo'\nerror: type mismatch"
        result = _trim_warnings(output)
        assert "unknown identifier" in result
        assert "type mismatch" in result

    def test_empty_input(self):
        """Empty string returns empty string."""
        assert _trim_warnings("") == ""

    def test_removes_trace_and_note(self):
        """Lines containing 'trace:' or 'note:' are removed."""
        output = "trace: [debug] some info\nnote: see declaration\nerror: real"
        result = _trim_warnings(output)
        assert "trace:" not in result
        assert "note:" not in result
        assert "real" in result


class TestFormatLeanErrors:
    """Tests for _format_lean_errors function."""

    def test_formats_error_with_context(self):
        """Error at a specific line gets formatted with code context."""
        file_content = "line 1\nline 2\nlet x := bad_expr\nline 4"
        error_output = "MyFile.lean:3:10: error: unknown identifier 'bad_expr'"
        result = _format_lean_errors(error_output, "MyFile.lean", file_content)
        assert "Error at line 3:10" in result
        assert "bad_expr" in result
        assert "^^^" in result

    def test_preserves_non_matching_lines(self):
        """Lines not matching the file pattern are passed through."""
        error_output = "some other output\ngeneral info"
        result = _format_lean_errors(error_output, "MyFile.lean", "content")
        assert "some other output" in result
        assert "general info" in result

    def test_handles_out_of_range_line(self):
        """Line number beyond file content doesn't crash."""
        file_content = "line 1"
        error_output = "MyFile.lean:99:1: error: something"
        # Should not raise
        result = _format_lean_errors(error_output, "MyFile.lean", file_content)
        assert result is not None

    def test_empty_output(self):
        """Empty error output returns empty string."""
        assert _format_lean_errors("", "MyFile.lean", "content") == ""


class TestTemporaryProposalTempLocation:
    """The temp Location created by TemporaryProposal must always resolve to the real on-disk temp
    file.

    The temp file is physically created under the project tree and addressed elsewhere via
    ``location.path``. Therefore ``location.absolute_path`` must agree with ``location.path`` and
    point at the actual temp file, so that cleanup, permanent apply, and post-build declaration
    listing operate on the right file (and never on ``None``).
    """

    @staticmethod
    def _empty_proposal() -> ProposalMessage:
        # No imports/opens/code -> the replace step in __enter__ is skipped, so we
        # exercise only the temp-file creation and location logic.
        return ProposalMessage(reasoning="noop", code="")

    def test_local_original_temp_resolves_to_disk(self, tmp_path):
        """A local original yields a temp location that resolves on disk."""
        src = tmp_path / "MyProj" / "Thing.lean"
        src.parent.mkdir(parents=True)
        src.write_text("theorem t : True := trivial\n", encoding="utf-8")

        target_item = TargetItem(
            location=Location(name="t", module_path="MyProj.Thing"),
            original_source="theorem t : True := trivial",
        )

        with TemporaryProposal(
            str(tmp_path), target_item, self._empty_proposal(), proposed_code=""
        ) as applier:
            assert applier.success, applier.error
            on_disk = Path(tmp_path) / applier.location.path
            assert on_disk.exists()
            assert applier.location.absolute_path(str(tmp_path)) == on_disk

        assert not on_disk.exists(), "temp file should be cleaned up on exit"
