"""Tests for build utility helper functions.

Generated by our friend.
"""

from pathlib import Path

from ax_prover.models.files import Location
from ax_prover.models.messages import ProposalMessage
from ax_prover.utils.build import TemporaryProposal, _format_lean_errors, _trim_warnings


class TestTrimWarnings:
    """Tests for _trim_warnings function."""

    def test_removes_warning_lines(self):
        """Lines containing 'warning:' are removed."""
        output = "error: type mismatch\nwarning: unused import\nother line"
        result = _trim_warnings(output)
        assert "warning:" not in result
        assert "error: type mismatch" in result
        assert "other line" in result

    def test_removes_sorry_warnings(self):
        """Lines about sorry usage are removed."""
        output = "declaration uses 'sorry'\nerror: real error"
        result = _trim_warnings(output)
        assert "sorry" not in result
        assert "real error" in result

    def test_removes_unused_variable_warnings(self):
        """Lines about unused variables are removed."""
        output = "unused variable `h`\ndef foo := 1"
        result = _trim_warnings(output)
        assert "unused variable" not in result

    def test_preserves_error_lines(self):
        """Error lines without warning keywords are preserved."""
        output = "error: unknown identifier 'foo'\nerror: type mismatch"
        result = _trim_warnings(output)
        assert "unknown identifier" in result
        assert "type mismatch" in result

    def test_empty_input(self):
        """Empty string returns empty string."""
        assert _trim_warnings("") == ""

    def test_removes_trace_and_note(self):
        """Lines containing 'trace:' or 'note:' are removed."""
        output = "trace: [debug] some info\nnote: see declaration\nerror: real"
        result = _trim_warnings(output)
        assert "trace:" not in result
        assert "note:" not in result
        assert "real" in result


class TestFormatLeanErrors:
    """Tests for _format_lean_errors function."""

    def test_formats_error_with_context(self):
        """Error at a specific line gets formatted with code context."""
        file_content = "line 1\nline 2\nlet x := bad_expr\nline 4"
        error_output = "MyFile.lean:3:10: error: unknown identifier 'bad_expr'"
        result = _format_lean_errors(error_output, "MyFile.lean", file_content)
        assert "Error at line 3:10" in result
        assert "bad_expr" in result
        assert "^^^" in result

    def test_preserves_non_matching_lines(self):
        """Lines not matching the file pattern are passed through."""
        error_output = "some other output\ngeneral info"
        result = _format_lean_errors(error_output, "MyFile.lean", "content")
        assert "some other output" in result
        assert "general info" in result

    def test_handles_out_of_range_line(self):
        """Line number beyond file content doesn't crash."""
        file_content = "line 1"
        error_output = "MyFile.lean:99:1: error: something"
        # Should not raise
        result = _format_lean_errors(error_output, "MyFile.lean", file_content)
        assert result is not None

    def test_empty_output(self):
        """Empty error output returns empty string."""
        assert _format_lean_errors("", "MyFile.lean", "content") == ""


def _make_demo_project(tmp_path) -> Location:
    """Write a minimal Lean file and return its Location."""
    (tmp_path / "Demo.lean").write_text(
        "import Existing.Module\n\ntheorem thm : True := trivial\n",
        encoding="utf-8",
    )
    return Location(name="thm", module_path="Demo", is_external=False)


def _make_namespaced_demo_project(tmp_path) -> Location:
    """Write a Lean file containing a `B.insert` target and return its Location.

    The file does not yet matter for selection (the proposal carries the new code);
    we just need a valid original file whose target declaration can be replaced.
    """
    (tmp_path / "Demo.lean").write_text(
        "namespace B\n\ndef insert : Nat := sorry\n\nend B\n",
        encoding="utf-8",
    )
    return Location(name="B.insert", module_path="Demo", is_external=False)


def test_temporary_proposal_selects_target_by_namespace(tmp_path):
    """When the proposal code has two same-simple-name decls, the namespace-qualified
    target (B.insert, the SECOND occurrence) is applied — not the first (A.insert)."""
    location = _make_namespaced_demo_project(tmp_path)
    proposal = ProposalMessage(
        reasoning="r",
        code=(
            "namespace A\n\n"
            "def insert : Nat := 111\n\n"
            "end A\n\n"
            "namespace B\n\n"
            "def insert : Nat := 222\n\n"
            "end B\n"
        ),
        location=location,
        imports=[],
        opens=[],
    )
    with TemporaryProposal(str(tmp_path), location, proposal) as applier:
        assert applier.success, applier.error
        content = (Path(tmp_path) / applier.location.path).read_text(encoding="utf-8")
        # The TARGET (B.insert, value 222) must be applied, not the first decl (A.insert).
        assert "222" in content
        assert "111" not in content


def test_temporary_proposal_single_declaration_regression(tmp_path):
    """The common case (single declaration, simple name, occurrence 0) is unchanged."""
    location = _make_demo_project(tmp_path)
    proposal = ProposalMessage(
        reasoning="r",
        code="theorem thm : True := by\n  exact trivial",
        location=location,
        imports=[],
        opens=[],
    )
    with TemporaryProposal(str(tmp_path), location, proposal) as applier:
        assert applier.success, applier.error
        content = (Path(tmp_path) / applier.location.path).read_text(encoding="utf-8")
        assert "exact trivial" in content
