"""Tests for LangSmith evaluators (pure data extraction functions).

Generated by our friend.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from ax_prover.config import ProverConfig
from ax_prover.evaluators import (
    build_timeout_count,
    compilation_error_count,
    is_proven,
    max_iterations_reached,
    number_of_iterations,
    reviewer_rejections,
    tool_usage,
)


def _fake_run(**kwargs):
    """A duck-typed stand-in for a LangSmith Run (evaluators access it by attribute)."""
    defaults = {
        "trace_id": "trace-1",
        "run_type": "chain",
        "name": "root",
        "prompt_tokens": None,
        "completion_tokens": None,
        "total_tokens": None,
    }
    defaults.update(kwargs)
    return SimpleNamespace(**defaults)


class TestIsProven:
    """Tests for is_proven evaluator."""

    @pytest.mark.parametrize(
        "outputs, expected",
        [
            ({"item": {"is_proven": True}}, True),
            ({"item": {"is_proven": False}}, False),
            ({"error": "some error"}, False),
            ({}, False),
            ({"item": {}}, False),
        ],
    )
    def test_is_proven(self, outputs, expected):
        """Returns correct proven status from outputs dict."""
        assert is_proven(outputs) == expected


class TestMetricEvaluators:
    """Tests for metric extraction evaluators."""

    @pytest.mark.parametrize(
        "func, key, value",
        [
            (number_of_iterations, "number_of_iterations", 5),
            (reviewer_rejections, "reviewer_rejections", 3),
            (compilation_error_count, "compilation_error_count", 2),
            (build_timeout_count, "build_timeout_count", 1),
        ],
    )
    def test_returns_value_when_present(self, func, key, value):
        """Returns the metric value when present in outputs."""
        assert func({"metrics": {key: value}}) == value

    @pytest.mark.parametrize(
        "func",
        [number_of_iterations, reviewer_rejections, compilation_error_count, build_timeout_count],
    )
    def test_returns_zero_when_missing(self, func):
        """Returns 0 when metrics key is absent."""
        assert func({}) == 0

    def test_max_iterations_reached_true(self):
        """Returns True when max_iterations_reached is True."""
        assert max_iterations_reached({"metrics": {"max_iterations_reached": True}}) is True

    def test_max_iterations_reached_default(self):
        """Returns False when metrics are missing."""
        assert max_iterations_reached({}) is False


class TestToolUsage:
    """Tests for the tool_usage evaluator (single list_runs, no retry/guard)."""

    def _config(self) -> ProverConfig:
        return ProverConfig(
            proposer_tools={"search_lean": {"tool_type": "search_lean_search"}},
        )

    def test_counts_tool_runs(self):
        """Counts tool runs from a single list_runs call."""
        runs = [
            SimpleNamespace(run_type="llm", name="deepseek"),
            SimpleNamespace(run_type="tool", name="search_lean_search_tool"),
            SimpleNamespace(run_type="tool", name="search_lean_search_tool"),
        ]
        mock = MagicMock()
        mock.list_runs.return_value = runs
        with patch("ax_prover.evaluators.Client", return_value=mock):
            result = tool_usage(_fake_run(), self._config())

        assert mock.list_runs.call_count == 1
        scores = {item["key"]: item["score"] for item in result}
        assert scores["tool_usage"] == 2
        assert scores["search_lean_search_tool"] == 2
