"""Tests for LangSmith evaluators (pure data extraction functions).

Generated by our friend.
"""

from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from ax_prover.config import LLMConfig, ProverConfig
from ax_prover.evaluators import (
    _compute_costs,
    build_timeout_count,
    compilation_error_count,
    is_proven,
    max_iterations_reached,
    number_of_iterations,
    reviewer_rejections,
    token_cost,
    tool_usage,
)


def _fake_run(**kwargs):
    """A duck-typed stand-in for a LangSmith Run (evaluators access it by attribute)."""
    defaults = {
        "trace_id": "trace-1",
        "run_type": "chain",
        "name": "root",
        "prompt_tokens": None,
        "completion_tokens": None,
        "total_tokens": None,
    }
    defaults.update(kwargs)
    return SimpleNamespace(**defaults)


class TestIsProven:
    """Tests for is_proven evaluator."""

    @pytest.mark.parametrize(
        "outputs, expected",
        [
            ({"item": {"is_proven": True}}, True),
            ({"item": {"is_proven": False}}, False),
            ({"error": "some error"}, False),
            ({}, False),
            ({"item": {}}, False),
        ],
    )
    def test_is_proven(self, outputs, expected):
        """Returns correct proven status from outputs dict."""
        assert is_proven(outputs) == expected


class TestMetricEvaluators:
    """Tests for metric extraction evaluators."""

    @pytest.mark.parametrize(
        "func, key, value",
        [
            (number_of_iterations, "number_of_iterations", 5),
            (reviewer_rejections, "reviewer_rejections", 3),
            (compilation_error_count, "compilation_error_count", 2),
            (build_timeout_count, "build_timeout_count", 1),
        ],
    )
    def test_returns_value_when_present(self, func, key, value):
        """Returns the metric value when present in outputs."""
        assert func({"metrics": {key: value}}) == value

    @pytest.mark.parametrize(
        "func",
        [number_of_iterations, reviewer_rejections, compilation_error_count, build_timeout_count],
    )
    def test_returns_zero_when_missing(self, func):
        """Returns 0 when metrics key is absent."""
        assert func({}) == 0

    def test_max_iterations_reached_true(self):
        """Returns True when max_iterations_reached is True."""
        assert max_iterations_reached({"metrics": {"max_iterations_reached": True}}) is True

    def test_max_iterations_reached_default(self):
        """Returns False when metrics are missing."""
        assert max_iterations_reached({}) is False


class TestComputeCosts:
    """Tests for the pure cost math."""

    def test_basic_costs(self):
        costs = _compute_costs(1_000_000, 2_000_000, 0.28, 0.42)
        assert costs["input_cost"] == pytest.approx(0.28)
        assert costs["output_cost"] == pytest.approx(0.84)
        assert costs["total_cost"] == pytest.approx(1.12)

    def test_zero_tokens(self):
        costs = _compute_costs(0, 0, 0.28, 0.42)
        assert costs == {"input_cost": 0.0, "output_cost": 0.0, "total_cost": 0.0}


def _prover_config_with_prices(input_price, output_price) -> ProverConfig:
    return ProverConfig(
        prover_llm=LLMConfig(
            model="deepseek-v4-pro",
            input_token_price=input_price,
            output_token_price=output_price,
        )
    )


class TestTokenCost:
    """Tests for the token_cost evaluator."""

    def test_returns_empty_when_prices_unset(self):
        """No feedback (and no error) when prices are not configured."""
        config = _prover_config_with_prices(None, None)
        assert token_cost(_fake_run(), config) == []

    def test_uses_aggregated_root_tokens(self):
        """Reads aggregated token counts off the root run without querying children."""
        config = _prover_config_with_prices(0.28, 0.42)
        run = _fake_run(prompt_tokens=1_000_000, completion_tokens=1_000_000)
        with patch("ax_prover.evaluators.Client") as mock_client:
            result = token_cost(run, config)
            mock_client.return_value.list_runs.assert_not_called()

        scores = {item["key"]: item["score"] for item in result}
        assert scores["input_cost"] == pytest.approx(0.28)
        assert scores["output_cost"] == pytest.approx(0.42)
        assert scores["total_cost"] == pytest.approx(0.70)

    def test_falls_back_to_summing_llm_runs(self):
        """When the root lacks token counts, sums the trace's LLM runs."""
        config = _prover_config_with_prices(1.0, 1.0)
        run = _fake_run(prompt_tokens=None, completion_tokens=None)
        llm_runs = [
            SimpleNamespace(run_type="llm", prompt_tokens=1_000_000, completion_tokens=500_000),
            SimpleNamespace(run_type="llm", prompt_tokens=1_000_000, completion_tokens=500_000),
            SimpleNamespace(run_type="tool", prompt_tokens=None, completion_tokens=None),
        ]
        with patch("ax_prover.evaluators.Client") as mock_client:
            mock_client.return_value.list_runs.return_value = llm_runs
            result = token_cost(run, config)

        scores = {item["key"]: item["score"] for item in result}
        assert scores["input_cost"] == pytest.approx(2.0)
        assert scores["output_cost"] == pytest.approx(1.0)
        assert scores["total_cost"] == pytest.approx(3.0)

    def test_returns_empty_on_client_error(self):
        """A LangSmith failure yields no feedback rather than erroring the row."""
        config = _prover_config_with_prices(0.28, 0.42)
        run = _fake_run(prompt_tokens=None, completion_tokens=None)
        with patch("ax_prover.evaluators.Client", side_effect=RuntimeError("boom")):
            assert token_cost(run, config) == []


class TestToolUsageHardening:
    """Tests for the hardened tool_usage evaluator."""

    def _config(self) -> ProverConfig:
        return ProverConfig(
            proposer_tools={"search_lean": {"tool_type": "search_lean_search"}},
        )

    def test_counts_tool_runs(self):
        runs = [
            SimpleNamespace(run_type="llm", name="deepseek"),
            SimpleNamespace(run_type="tool", name="search_lean_search_tool"),
            SimpleNamespace(run_type="tool", name="search_lean_search_tool"),
        ]
        with patch("ax_prover.evaluators.Client") as mock_client:
            mock_client.return_value.list_runs.return_value = runs
            result = tool_usage(_fake_run(), self._config())

        scores = {item["key"]: item["score"] for item in result}
        assert scores["tool_usage"] == 2
        assert scores["search_lean_search_tool"] == 2

    def test_never_raises_on_client_error(self):
        """A LangSmith failure reports zeros instead of throwing."""
        with patch("ax_prover.evaluators.Client", side_effect=RuntimeError("network down")):
            result = tool_usage(_fake_run(), self._config())

        scores = {item["key"]: item["score"] for item in result}
        assert scores["tool_usage"] == 0
        assert scores["search_lean_search_tool"] == 0

    def test_retries_until_trace_is_populated(self):
        """Retries listing runs while the trace has not yet flushed an LLM run."""
        empty = []
        populated = [
            SimpleNamespace(run_type="llm", name="deepseek"),
            SimpleNamespace(run_type="tool", name="search_lean_search_tool"),
        ]
        mock = MagicMock()
        mock.list_runs.side_effect = [empty, populated]
        with (
            patch("ax_prover.evaluators.Client", return_value=mock),
            patch("ax_prover.evaluators.time.sleep") as mock_sleep,
        ):
            result = tool_usage(_fake_run(), self._config())

        assert mock.list_runs.call_count == 2
        mock_sleep.assert_called_once()
        scores = {item["key"]: item["score"] for item in result}
        assert scores["search_lean_search_tool"] == 1
